In [24]:
import pandas as pd
import numpy as np

orders = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1003, 1004, 1005, 1006, 1007],
    
    "customer": [
        "Alex",
        "Maria ",
        "JAMES",
        "JAMES",
        "Sarah",
        None,
        "Alex",
        " maria"
    ],
    
    "state": [
        "CA",
        "ca",
        "TX",
        "TX",
        "NY",
        "CA",
        None,
        "CA"
    ],
    
    "quantity": [
        2,
        1,
        3,
        3,
        None,
        2,
        1,
        2
    ],
    
    "price": [
        300,
        1200,
        100,
        100,
        500,
        None,
        300,
        250
    ],
    
    "order_date": [
        "2026-01-05",
        "2026-01-07",
        "2026-01-10",
        "2026-01-10",
        "2026-01-15",
        "2026-01-18",
        "2026-01-20",
        "2026-01-22"
    ]
})

display(orders)

   order_id customer state  quantity   price  order_date
0      1001     Alex    CA       2.0   300.0  2026-01-05
1      1002   Maria     ca       1.0  1200.0  2026-01-07
2      1003    JAMES    TX       3.0   100.0  2026-01-10
3      1003    JAMES    TX       3.0   100.0  2026-01-10
4      1004    Sarah    NY       NaN   500.0  2026-01-15
5      1005      NaN    CA       2.0     NaN  2026-01-18
6      1006     Alex   NaN       1.0   300.0  2026-01-20
7      1007    maria    CA       2.0   250.0  2026-01-22

In [2]:
orders.head()

   order_id customer state  quantity   price  order_date
0      1001     Alex    CA       2.0   300.0  2026-01-05
1      1002   Maria     ca       1.0  1200.0  2026-01-07
2      1003    JAMES    TX       3.0   100.0  2026-01-10
3      1003    JAMES    TX       3.0   100.0  2026-01-10
4      1004    Sarah    NY       NaN   500.0  2026-01-15

In [3]:
orders.tail()

   order_id customer state  quantity  price  order_date
3      1003    JAMES    TX       3.0  100.0  2026-01-10
4      1004    Sarah    NY       NaN  500.0  2026-01-15
5      1005      NaN    CA       2.0    NaN  2026-01-18
6      1006     Alex   NaN       1.0  300.0  2026-01-20
7      1007    maria    CA       2.0  250.0  2026-01-22

In [4]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    8 non-null      int64
 1   customer    7 non-null      str
 2   state       7 non-null      str
 3   quantity    7 non-null      float64
 4   price       7 non-null      float64
 5   order_date  8 non-null      str
dtypes: float64(2), int64(1), str(3)
memory usage: 516.0 bytes

In [5]:
orders.columns

Index(['order_id', 'customer', 'state', 'quantity', 'price', 'order_date'], dtype='str')

In [6]:
orders.dtypes

order_id        int64
customer          str
state             str
quantity      float64
price         float64
order_date        str
dtype: object

In [7]:
orders.shape

(8, 6)

In [8]:
orders.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
dtype: bool

In [25]:
orders = orders.drop_duplicates()

In [10]:
orders.shape

(7, 6)

In [11]:
orders.isna()

   order_id  customer  state  quantity  price  order_date
0     False     False  False     False  False       False
1     False     False  False     False  False       False
2     False     False  False     False  False       False
4     False     False  False      True  False       False
5     False      True  False     False   True       False
6     False     False   True     False  False       False
7     False     False  False     False  False       False

In [12]:
orders.isna().sum()

order_id      0
customer      1
state         1
quantity      1
price         1
order_date    0
dtype: int64

In [13]:
orders.isna().any(axis=1)

0    False
1    False
2    False
4     True
5     True
6     True
7    False
dtype: bool

In [21]:
orders[orders.isna().any(axis=1)]

   order_id customer state  quantity  price  order_date
4      1004    Sarah    NY       NaN  500.0  2026-01-15
5      1005      NaN    CA       2.0    NaN  2026-01-18
6      1006     Alex   NaN       1.0  300.0  2026-01-20

In [26]:
orders["quantity"] = orders["quantity"].fillna(1)

In [27]:
display(orders)

   order_id customer state  quantity   price  order_date
0      1001     Alex    CA       2.0   300.0  2026-01-05
1      1002   Maria     ca       1.0  1200.0  2026-01-07
2      1003    JAMES    TX       3.0   100.0  2026-01-10
4      1004    Sarah    NY       1.0   500.0  2026-01-15
5      1005      NaN    CA       2.0     NaN  2026-01-18
6      1006     Alex   NaN       1.0   300.0  2026-01-20
7      1007    maria    CA       2.0   250.0  2026-01-22

In [28]:
orders["customer"] = orders["customer"].str.strip().str.title()

In [29]:
display(orders)

   order_id customer state  quantity   price  order_date
0      1001     Alex    CA       2.0   300.0  2026-01-05
1      1002    Maria    ca       1.0  1200.0  2026-01-07
2      1003    James    TX       3.0   100.0  2026-01-10
4      1004    Sarah    NY       1.0   500.0  2026-01-15
5      1005      NaN    CA       2.0     NaN  2026-01-18
6      1006     Alex   NaN       1.0   300.0  2026-01-20
7      1007    Maria    CA       2.0   250.0  2026-01-22

In [30]:
orders["state"] = orders["state"].str.strip().str.upper()

In [31]:
display(orders)

   order_id customer state  quantity   price  order_date
0      1001     Alex    CA       2.0   300.0  2026-01-05
1      1002    Maria    CA       1.0  1200.0  2026-01-07
2      1003    James    TX       3.0   100.0  2026-01-10
4      1004    Sarah    NY       1.0   500.0  2026-01-15
5      1005      NaN    CA       2.0     NaN  2026-01-18
6      1006     Alex   NaN       1.0   300.0  2026-01-20
7      1007    Maria    CA       2.0   250.0  2026-01-22

In [32]:
orders[["customer", "state"]]

  customer state
0     Alex    CA
1    Maria    CA
2    James    TX
4    Sarah    NY
5      NaN    CA
6     Alex   NaN
7    Maria    CA

In [33]:
orders['order_date'] = pd.to_datetime(orders['order_date'])

In [34]:
orders['order_date']

0   2026-01-05
1   2026-01-07
2   2026-01-10
4   2026-01-15
5   2026-01-18
6   2026-01-20
7   2026-01-22
Name: order_date, dtype: datetime64[us]

In [35]:
orders.dtypes

order_id               int64
customer                 str
state                    str
quantity             float64
price                float64
order_date    datetime64[us]
dtype: object

In [36]:
orders = orders.dropna(subset=["price"])

In [37]:
orders.shape

(6, 6)

In [38]:
orders.isna().sum()

order_id      0
customer      0
state         1
quantity      0
price         0
order_date    0
dtype: int64

Hour 1 — Final Cleaning Challenge

In [39]:
employees = pd.DataFrame({
    "employee_id": [1, 2, 2, 3, 4, 5],
    "name": [" alex ", "MARIA", "MARIA", "James ", "sarah", "David"],
    "department": ["sales", "FINANCE", "FINANCE", "Sales", "hr", "HR"],
    "salary": [70000, 85000, 85000, None, 65000, 72000],
    "hire_date": [
        "2024-01-10",
        "2023-06-15",
        "2023-06-15",
        "2025-02-01",
        "2024-08-20",
        "2025-05-10"
    ]
})

display(employees)

   employee_id    name department   salary   hire_date
0            1   alex       sales  70000.0  2024-01-10
1            2   MARIA    FINANCE  85000.0  2023-06-15
2            2   MARIA    FINANCE  85000.0  2023-06-15
3            3  James       Sales      NaN  2025-02-01
4            4   sarah         hr  65000.0  2024-08-20
5            5   David         HR  72000.0  2025-05-10

Your job is to clean it so that:  

- Duplicate rows are removed.  
- name has no leading/trailing spaces and uses title case.  
- department is uppercase.  
- hire_date becomes a proper datetime.  
- Rows with a missing salary are removed.

In [40]:
employees.shape

(6, 5)

In [43]:
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  6 non-null      int64
 1   name         6 non-null      str
 2   department   6 non-null      str
 3   salary       5 non-null      float64
 4   hire_date    6 non-null      str
dtypes: float64(1), int64(1), str(3)
memory usage: 372.0 bytes

In [42]:
employees.dtypes

employee_id      int64
name               str
department         str
salary         float64
hire_date          str
dtype: object

In [44]:
#remove duplicates
employees = employees.drop_duplicates()

In [47]:
employees.shape
display(employees)

   employee_id    name department   salary   hire_date
0            1   alex       sales  70000.0  2024-01-10
1            2   MARIA    FINANCE  85000.0  2023-06-15
3            3  James       Sales      NaN  2025-02-01
4            4   sarah         hr  65000.0  2024-08-20
5            5   David         HR  72000.0  2025-05-10

In [49]:
#name has no leading/trailing spaces and uses title case.
employees["name"] = employees["name"].str.strip().str.title()
display(employees)

   employee_id   name department   salary   hire_date
0            1   Alex      sales  70000.0  2024-01-10
1            2  Maria    FINANCE  85000.0  2023-06-15
3            3  James      Sales      NaN  2025-02-01
4            4  Sarah         hr  65000.0  2024-08-20
5            5  David         HR  72000.0  2025-05-10

In [50]:
#department is uppercase.#
employees["department"] = employees["department"].str.strip().str.upper()
display(employees)

   employee_id   name department   salary   hire_date
0            1   Alex      SALES  70000.0  2024-01-10
1            2  Maria    FINANCE  85000.0  2023-06-15
3            3  James      SALES      NaN  2025-02-01
4            4  Sarah         HR  65000.0  2024-08-20
5            5  David         HR  72000.0  2025-05-10

In [51]:
#hire_date becomes a proper datetime.
employees['hire_date'] = pd.to_datetime(employees['hire_date'])
employees.dtypes

employee_id             int64
name                      str
department                str
salary                float64
hire_date      datetime64[us]
dtype: object

In [52]:
#Rows with a missing salary are removed.
employees = employees.dropna(subset=["salary"])
display(employees)

   employee_id   name department   salary  hire_date
0            1   Alex      SALES  70000.0 2024-01-10
1            2  Maria    FINANCE  85000.0 2023-06-15
4            4  Sarah         HR  65000.0 2024-08-20
5            5  David         HR  72000.0 2025-05-10

# Hour 2: Pandas transformations — calculated columns

In [1]:
import pandas as pd
import numpy as np

sales = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
    "customer": ["Alex", "Maria", "James", "Sarah", "Alex", "Maria", "James", "Alex"],
    "state": ["CA", "CA", "TX", "NY", "CA", "CA", "TX", "CA"],
    "product": ["Monitor", "Laptop", "Keyboard", "Monitor", "Laptop", "Keyboard", "Monitor", "Keyboard"],
    "quantity": [2, 1, 3, 1, 1, 2, 2, 4],
    "price": [300, 1200, 100, 300, 1200, 100, 300, 100]
})

display(sales)

   order_id customer state   product  quantity  price
0      1001     Alex    CA   Monitor         2    300
1      1002    Maria    CA    Laptop         1   1200
2      1003    James    TX  Keyboard         3    100
3      1004    Sarah    NY   Monitor         1    300
4      1005     Alex    CA    Laptop         1   1200
5      1006    Maria    CA  Keyboard         2    100
6      1007    James    TX   Monitor         2    300
7      1008     Alex    CA  Keyboard         4    100

In [3]:
#df["new_column"] = calculation
sales["total_sales"] = sales["quantity"] * sales["price"]

sales.head()

   order_id customer state   product  quantity  price  total_sales
0      1001     Alex    CA   Monitor         2    300          600
1      1002    Maria    CA    Laptop         1   1200         1200
2      1003    James    TX  Keyboard         3    100          300
3      1004    Sarah    NY   Monitor         1    300          300
4      1005     Alex    CA    Laptop         1   1200         1200

In [4]:
sales.groupby("product")["quantity"].sum()

product
Keyboard    9
Laptop      2
Monitor     5
Name: quantity, dtype: int64

In [5]:
sales.groupby("product")["quantity"].sum().reset_index()

    product  quantity
0  Keyboard         9
1    Laptop         2
2   Monitor         5

In [7]:
sales.groupby("customer")["total_sales"].sum().reset_index()

  customer  total_sales
0     Alex         2200
1    James          900
2    Maria         1400
3    Sarah          300

In [8]:
display(sales)

   order_id customer state   product  quantity  price  total_sales
0      1001     Alex    CA   Monitor         2    300          600
1      1002    Maria    CA    Laptop         1   1200         1200
2      1003    James    TX  Keyboard         3    100          300
3      1004    Sarah    NY   Monitor         1    300          300
4      1005     Alex    CA    Laptop         1   1200         1200
5      1006    Maria    CA  Keyboard         2    100          200
6      1007    James    TX   Monitor         2    300          600
7      1008     Alex    CA  Keyboard         4    100          400

In [ ]:
sales.groupby("state").agg(
    total_sales=(""total_sales","sum""),
    average_sales=("total_sales","mean"),
    total_quantity=("quantity", "sum")
).reset_index()

  state  total_sales  average_sales  total_quantity
0    CA         3600          720.0              10
1    NY          300          300.0               1
2    TX          900          450.0               5

In [10]:
sales.groupby("state").agg(
    total_sales=("total_sales","sum"),
    average_sales=("total_sales","mean"),
    total_quantity=("quantity", "sum"),
    order_count=("order_id","count")
).reset_index()

  state  total_sales  average_sales  total_quantity  order_count
0    CA         3600          720.0              10            5
1    NY          300          300.0               1            1
2    TX          900          450.0               5            2

In [12]:
sales.groupby(["state","product"]).agg(
    total_sales=("total_sales", "sum"),
    total_quantity=("quantity","sum")
).reset_index()

  state   product  total_sales  total_quantity
0    CA  Keyboard          600               6
1    CA    Laptop         2400               2
2    CA   Monitor          600               2
3    NY   Monitor          300               1
4    TX  Keyboard          300               3
5    TX   Monitor          600               2

In [15]:
product_summary = sales.groupby("product").agg(
    total_sales=("total_sales", "sum"),
    total_quantity=("quantity", "sum")
).reset_index()

display(product_summary)

    product  total_sales  total_quantity
0  Keyboard          900               9
1    Laptop         2400               2
2   Monitor         1500               5

In [16]:
product_summary[product_summary["total_quantity"] >= 5]

    product  total_sales  total_quantity
0  Keyboard          900               9
2   Monitor         1500               5

Which customers have generated at least $1,000 in sales, and what are their total sales, total quantity purchased, and number of orders?

In [17]:
display(sales)

   order_id customer state   product  quantity  price  total_sales
0      1001     Alex    CA   Monitor         2    300          600
1      1002    Maria    CA    Laptop         1   1200         1200
2      1003    James    TX  Keyboard         3    100          300
3      1004    Sarah    NY   Monitor         1    300          300
4      1005     Alex    CA    Laptop         1   1200         1200
5      1006    Maria    CA  Keyboard         2    100          200
6      1007    James    TX   Monitor         2    300          600
7      1008     Alex    CA  Keyboard         4    100          400

In [18]:
customer_sales = sales.groupby("customer").agg(
    total_sales = ("total_sales","sum"),
    total_quantity = ("quantity", "sum"),
    order_count = ("order_id", "count")
).reset_index()

display(customer_sales)

  customer  total_sales  total_quantity  order_count
0     Alex         2200               7            3
1    James          900               5            2
2    Maria         1400               3            2
3    Sarah          300               1            1

In [20]:
customer_sales[customer_sales["total_sales"] >= 1000].sort_values("total_sales", ascending=False)

  customer  total_sales  total_quantity  order_count
0     Alex         2200               7            3
2    Maria         1400               3            2

Hour 3: Combining DataFrames with merge()

In [2]:
import pandas as pd
import numpy as np

customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "customer_name": ["Alex", "Maria", "James", "Sarah"],
    "state": ["CA", "CA", "TX", "NY"]
})

orders = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1004, 1005],
    "customer_id": [1, 1, 2, 3, 3],
    "product_id": [10, 11, 10, 12, 11],
    "quantity": [2, 1, 1, 3, 2]
})

products = pd.DataFrame({
    "product_id": [10, 11, 12],
    "product_name": ["Laptop", "Monitor", "Keyboard"],
    "price": [1200, 300, 100]
})

display(customers)
display(orders)
display(products)

   customer_id customer_name state
0            1          Alex    CA
1            2         Maria    CA
2            3         James    TX
3            4         Sarah    NY

   order_id  customer_id  product_id  quantity
0      1001            1          10         2
1      1002            1          11         1
2      1003            2          10         1
3      1004            3          12         3
4      1005            3          11         2

   product_id product_name  price
0          10       Laptop   1200
1          11      Monitor    300
2          12     Keyboard    100

Merge orders with customers

In [3]:
# pd.merge(
#     left_dataframe,
#     right_dataframe,
#     on="key_column"
# )

In [5]:
orders_customers = pd.merge(
    orders,
    customers,
    on="customer_id"
)

display(orders_customers)

   order_id  customer_id  product_id  quantity customer_name state
0      1001            1          10         2          Alex    CA
1      1002            1          11         1          Alex    CA
2      1003            2          10         1         Maria    CA
3      1004            3          12         3         James    TX
4      1005            3          11         2         James    TX

In [6]:
all_customers = pd.merge(
    customers,
    orders,
    on="customer_id",
    how="left")

display(all_customers)

   customer_id customer_name state  order_id  product_id  quantity
0            1          Alex    CA    1001.0        10.0       2.0
1            1          Alex    CA    1002.0        11.0       1.0
2            2         Maria    CA    1003.0        10.0       1.0
3            3         James    TX    1004.0        12.0       3.0
4            3         James    TX    1005.0        11.0       2.0
5            4         Sarah    NY       NaN         NaN       NaN

In [7]:
full_sales = pd.merge(
    orders_customers,
    products,
    on="product_id")

display(full_sales)

,order_id,customer_id,product_id,quantity,customer_name,state,product_name,price
0,1001,1,10,2,Alex,CA,Laptop,1200
1,1002,1,11,1,Alex,CA,Monitor,300
2,1003,2,10,1,Maria,CA,Laptop,1200
3,1004,3,12,3,James,TX,Keyboard,100
4,1005,3,11,2,James,TX,Monitor,300

In [13]:
full_sales["total_sales"] = full_sales["quantity"]*full_sales["price"]

full_sales[["order_id","customer_name","product_name","quantity","price","total_sales"]]

   order_id customer_name product_name  quantity  price  total_sales
0      1001          Alex       Laptop         2   1200         2400
1      1002          Alex      Monitor         1    300          300
2      1003         Maria       Laptop         1   1200         1200
3      1004         James     Keyboard         3    100          300
4      1005         James      Monitor         2    300          600

In [14]:
orders.shape

(5, 4)

In [15]:
full_sales.shape

(5, 9)

In [16]:
display(customers)
display(orders)
display(products)

   customer_id customer_name state
0            1          Alex    CA
1            2         Maria    CA
2            3         James    TX
3            4         Sarah    NY

   order_id  customer_id  product_id  quantity
0      1001            1          10         2
1      1002            1          11         1
2      1003            2          10         1
3      1004            3          12         3
4      1005            3          11         2

   product_id product_name  price
0          10       Laptop   1200
1          11      Monitor    300
2          12     Keyboard    100

In [20]:
orders_customers_2 = pd.merge(
    orders,
    customers,
    on="customer_id",
    validate="many_to_one"
)

display(orders_customers_2)

   order_id  customer_id  product_id  quantity customer_name state
0      1001            1          10         2          Alex    CA
1      1002            1          11         1          Alex    CA
2      1003            2          10         1         Maria    CA
3      1004            3          12         3         James    TX
4      1005            3          11         2         James    TX

In [19]:
orders_customers_2.shape

(5, 6)

In [21]:
sales_analysis = pd.merge(
    orders_customers_2,
    products,
    on="product_id",
    validate="many_to_one"
)

display(sales_analysis)

,order_id,customer_id,product_id,quantity,customer_name,state,product_name,price
0,1001,1,10,2,Alex,CA,Laptop,1200
1,1002,1,11,1,Alex,CA,Monitor,300
2,1003,2,10,1,Maria,CA,Laptop,1200
3,1004,3,12,3,James,TX,Keyboard,100
4,1005,3,11,2,James,TX,Monitor,300

In [22]:
sales_analysis.shape

(5, 8)

In [23]:
sales_analysis["total_sales"] = sales_analysis["quantity"] * sales_analysis["price"]

In [24]:
sales_analysis.sort_values("total_sales",ascending=False)

,order_id,customer_id,product_id,quantity,customer_name,state,product_name,price,total_sales
0,1001,1,10,2,Alex,CA,Laptop,1200,2400
2,1003,2,10,1,Maria,CA,Laptop,1200,1200
4,1005,3,11,2,James,TX,Monitor,300,600
1,1002,1,11,1,Alex,CA,Monitor,300,300
3,1004,3,12,3,James,TX,Keyboard,100,300

In [25]:
sales_analysis = sales_analysis.sort_values("total_sales",ascending=False)
display(sales_analysis)

,order_id,customer_id,product_id,quantity,customer_name,state,product_name,price,total_sales
0,1001,1,10,2,Alex,CA,Laptop,1200,2400
2,1003,2,10,1,Maria,CA,Laptop,1200,1200
4,1005,3,11,2,James,TX,Monitor,300,600
1,1002,1,11,1,Alex,CA,Monitor,300,300
3,1004,3,12,3,James,TX,Keyboard,100,300